name: Test WorkerPool
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.24.2
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'

      - name: Install dependencies
        run: go mod tidy

      - name: Test with the Go CLI
        run: go test ./...
